(pixel-scroll-mode 1)
(savehist-mode 1)
(tool-bar-mode -1)
(menu-bar-mode -1)
(scroll-bar-mode -1)
(setq inhibit-splash-screen t)
(setq inhibit-startup-message t)

(set-frame-font "PragmataPro-12")
(add-to-list 'default-frame-alist '(font . "PragmataPro-12"))
