(require 'centaur-tabs)
(global-set-key (kbd "C-<prior>")  'centaur-tabs-backward)
(global-set-key (kbd "C-<next>") 'centaur-tabs-forward)
(centaur-tabs-headline-match)
;; (setq centaur-tabs-style "slant")
(setq centaur-tabs-set-icons t)
;; (setq centaur-tabs-set-bar 'over)
;; (setq centaur-tabs-set-modified-marker t)
(centaur-tabs-mode t)
